[wokwi]
version = 1
gdbServerPort = 3333
firmware = '.pio/build/debug-local/firmware.bin'
elf = '.pio/build/debug-local/firmware.elf'

[[wokwi.scenario.controls]]
part-id = "esp"
control = "25"

[[wokwi.scenario.controls]]
part-id = "esp"
control = "26"

[[wokwi.scenario.controls]]
part-id = "esp"
control = "27"

[[wokwi.scenario.controls]]
part-id = "esp"
control = "32"