#pragma once

#include "utilities/types.h"
#include "utilities/constants.h"
#include "managers/panel_manager.h"
#include "managers/style_manager.h"

/**
 * @file system_definitions.h
 * @brief System trigger and action definitions for the new interrupt architecture
 * 
 * @details This file contains all the system-wide trigger and action definitions
 * exactly as specified in docs/interrupt-architecture.md. These definitions
 * implement the modern Trigger/Action separation architecture.
 */

namespace SystemDefinitions {

/// @brief Get all system triggers as documented in interrupt-architecture.md
/// @param keyPresentSensor Pointer to the key present sensor
/// @param keyNotPresentSensor Pointer to the key not present sensor  
/// @param lockSensor Pointer to the lock sensor
/// @param lightsSensor Pointer to the lights sensor
/// @param errorSensor Pointer to the error sensor (if available)
/// @return Array of system triggers
inline std::vector<Trigger> GetSystemTriggers(
    class BaseSensor* keyPresentSensor,
    class BaseSensor* keyNotPresentSensor, 
    class BaseSensor* lockSensor,
    class BaseSensor* lightsSensor,
    class BaseSensor* errorSensor = nullptr) {
    
    std::vector<Trigger> triggers = {
        // Key triggers - CRITICAL priority
        {
            .id = "key_present",
            .priority = Priority::CRITICAL,
            .type = TriggerType::PANEL,
            .activateFunc = []() { PanelManager::TriggerService().LoadPanel(PanelNames::KEY); },
            .deactivateFunc = []() { PanelManager::TriggerService().CheckRestoration(); },
            .sensor = keyPresentSensor,
            .isActive = false
        },
        {
            .id = "key_not_present", 
            .priority = Priority::CRITICAL,
            .type = TriggerType::PANEL,
            .activateFunc = []() { PanelManager::TriggerService().LoadPanel(PanelNames::KEY); },
            .deactivateFunc = []() { PanelManager::TriggerService().CheckRestoration(); },
            .sensor = keyNotPresentSensor,
            .isActive = false
        },
        
        // Lock trigger - IMPORTANT priority
        {
            .id = "lock",
            .priority = Priority::IMPORTANT,
            .type = TriggerType::PANEL,
            .activateFunc = []() { PanelManager::TriggerService().LoadPanel(PanelNames::LOCK); },
            .deactivateFunc = []() { PanelManager::TriggerService().CheckRestoration(); },
            .sensor = lockSensor,
            .isActive = false
        },
        
        // Lights trigger - NORMAL priority
        {
            .id = "lights",
            .priority = Priority::NORMAL,
            .type = TriggerType::STYLE,
            .activateFunc = []() { StyleManager::Instance().SetTheme(Themes::NIGHT); },
            .deactivateFunc = []() { StyleManager::Instance().SetTheme(Themes::DAY); },
            .sensor = lightsSensor,
            .isActive = false
        }
    };
    
    // Add error trigger if sensor is provided
    // Note: This is a simple event trigger - it doesn't maintain state or activate/deactivate
    // The sensor generates errors when button is pressed, error panel loading is handled automatically
    if (errorSensor) {
        triggers.push_back({
            .id = "error",
            .priority = Priority::CRITICAL,
            .type = TriggerType::PANEL,  // Keep as PANEL type for priority handling
            .activateFunc = []() { 
                // Check if error queue is empty - if so, don't re-trigger
                // This prevents restoration from re-executing after long press clears errors
                if (!ErrorManager::Instance().HasPendingErrors()) {
                    log_d("Debug error trigger activated but no errors - restoration after clear, ignoring");
                    return;
                }
                log_d("Debug error button pressed - errors already generated by sensor");
            },
            .deactivateFunc = []() { 
                // No-op: Push button doesn't have deactivation, no restoration needed
                log_d("Debug error trigger deactivate - no action needed for push button");
            },
            .sensor = errorSensor,
            .isActive = false
        });
    }
    
    return triggers;
}

/// @brief Get all system actions as documented in interrupt-architecture.md
/// @return Array of system actions
inline std::vector<Action> GetSystemActions() {
    return {
        // Button actions
        {
            .id = "short_press",
            .executeFunc = []() { PanelManager::ActionService().HandleShortPress(); },
            .hasTriggered = false,
            .pressType = ActionPress::SHORT
        },
        {
            .id = "long_press",
            .executeFunc = []() { PanelManager::ActionService().HandleLongPress(); },
            .hasTriggered = false,
            .pressType = ActionPress::LONG
        }
    };
}

} // namespace SystemDefinitions