name: Wokwi Basic Hardware Test

on:
  push:
    branches: [ main, develop, "feature/*", "fix/*", "hotfix/*" ]
  workflow_dispatch:

jobs:
  basic-hardware-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: |
          ~/.platformio/.cache
          ~/.platformio/penv
        key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
          
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Install Wokwi CLI
      run: |
        curl -L https://wokwi.com/ci/install.sh | sh
        echo "$HOME/.wokwi/bin" >> $GITHUB_PATH
        
    - name: Verify installations
      run: |
        pio --version
        wokwi-cli --version
        
    - name: Build firmware
      run: |
        pio run -e test-wokwi-basic
        
    - name: Run basic hardware test
      env:
        WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
      run: |
        chmod +x ./test/wokwi/run_test.sh
        ./test/wokwi/run_test.sh basic
        
    - name: Upload build artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-basic
        path: |
          .pio/build/test-wokwi-basic/
          test/wokwi/wokwi.toml
        retention-days: 3