name: Wokwi Release Validation Tests

on:
  push:
    branches: [ "release/*" ]
    tags: [ "v*.*.*" ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type to run'
        required: true
        default: 'both'
        type: choice
        options:
        - basic
        - full
        - both

jobs:
  release-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    strategy:
      matrix:
        test_type: ${{ github.event_name == 'workflow_dispatch' && fromJson(format('["basic", "full"]')) || fromJson('["basic", "full"]') }}
        exclude:
          - test_type: ${{ github.event.inputs.test_type == 'basic' && 'full' || 'none' }}
          - test_type: ${{ github.event.inputs.test_type == 'full' && 'basic' || 'none' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: |
          ~/.platformio/.cache
          ~/.platformio/penv
        key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
          
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Install Wokwi CLI
      run: |
        curl -L https://wokwi.com/ci/install.sh | sh
        echo "$HOME/.wokwi/bin" >> $GITHUB_PATH
        
    - name: Verify installations
      run: |
        pio --version
        wokwi-cli --version
        
    - name: Build firmware
      run: |
        pio run -e test-wokwi-${{ matrix.test_type }}
        
    - name: Run ${{ matrix.test_type }} test
      env:
        WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
      run: |
        chmod +x ./test/wokwi/run_test.sh
        ./test/wokwi/run_test.sh ${{ matrix.test_type }}
        
    - name: Upload build artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-${{ matrix.test_type }}-release
        path: |
          .pio/build/test-wokwi-${{ matrix.test_type }}/
          test/wokwi/wokwi.toml
        retention-days: 14