name: Wokwi Full System Integration Test

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:

jobs:
  full-integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    # Skip draft PRs unless explicitly requested
    if: github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: |
          ~/.platformio/.cache
          ~/.platformio/penv
        key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
          
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Install Wokwi CLI
      run: |
        curl -L https://wokwi.com/ci/install.sh | sh
        echo "$HOME/.wokwi/bin" >> $GITHUB_PATH
        
    - name: Verify installations
      run: |
        pio --version
        wokwi-cli --version
        
    - name: Build firmware
      run: |
        pio run -e test-wokwi-full
        
    - name: Run full system integration test
      env:
        WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
      run: |
        chmod +x ./test/wokwi/run_test.sh
        ./test/wokwi/run_test.sh full
        
    - name: Comment PR with test results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo, number } = context.issue;
          const success = '${{ job.status }}' === 'success';
          const body = success 
            ? '✅ **Full System Integration Test PASSED**\n\nAll 7 phases completed successfully with 100% test coverage:\n- System Startup & Initial State\n- Sensor Data & Animations\n- Trigger System Testing\n- Error Handling System\n- Trigger Deactivation & Theme Changes\n- Configuration System Testing\n- Final System Validation\n\n*Duration: ~2 minutes*'
            : '❌ **Full System Integration Test FAILED**\n\nPlease check the workflow logs for details. The test covers complete system integration including all panels, triggers, animations, and user interactions.';
          
          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body
          });
        
    - name: Upload build artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-full
        path: |
          .pio/build/test-wokwi-full/
          test/wokwi/wokwi.toml
        retention-days: 7
        
    - name: Upload test logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-logs-full
        path: |
          /tmp/wokwi_output_*
        retention-days: 7
        if-no-files-found: ignore